FROM python:3.11-slim



WORKDIR /app



ENV PYTHONUNBUFFERED=1

ENV PYTHONDONTWRITEBYTECODE=1



COPY pyproject.toml .



RUN pip install --upgrade pip


RUN pip install streamlit httpx



COPY streamlit ./streamlit



EXPOSE 8501



CMD [

    "streamlit",

    "run",

    "streamlit/app.py",

    "--server.address=0.0.0.0",

    "--server.port=8501"

]
