FROM python:3.11-slim


WORKDIR /app



# Prevent Python buffering
ENV PYTHONUNBUFFERED=1


# Prevent .pyc creation
ENV PYTHONDONTWRITEBYTECODE=1



# Install system dependencies

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*



# Copy project configuration

COPY pyproject.toml .



# Install Python dependencies

RUN pip install --upgrade pip

RUN pip install .



# Copy application source

COPY src ./src

COPY data ./data



# API port

EXPOSE 8000



CMD [
    "uvicorn",
    "src.main:app",
    "--host",
    "0.0.0.0",
    "--port",
    "8000"
]
